name: Build Releases Windows

on:
  workflow_call:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: ""

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract tag from release
        id: extract_tag
        shell: bash
        run: |
          TAG=$(gh api repos/${{ github.repository }}/releases \
            --jq '.[0].tag_name')
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          targets: |
            x86_64-pc-windows-msvc
            i686-pc-windows-msvc
            aarch64-pc-windows-msvc

      - name: Install WiX Toolset
        uses: microsoft/setup-msbuild@v1

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build MSI (x86, x64, arm64)
        run: |
          powershell.exe ./build-msi/build.ps1

      - name: Upload Release Asset
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          tag: ${{ steps.extract_tag.outputs.tag }}
          artifacts: |
            build/clippy-*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
